### ISSUE TITLE
RewindScanner 가 파일 끝을 빈줄을 기준으로 인식합니다.

### ISSUE THREAD

**Issue by mrchypark** [codingpot/kiwigo#27]
그래서 전체 택스트에서 빈 줄이 있으면 다음줄을 확인하지 않고 종료로 판단하여 다 읽어오지 않음.

**Comment by mrchypark** [comment]
https://gosamples.dev/read-file/

scarn.Error() 로 끝을 확인하는 건지 확인 필요.

**Comment by kkweon** [comment]
계속 Scan 하면 될텐데요?

**Comment by mrchypark** [comment]
현재 코드는 최초 Scan() 에서 false가 나오면 종료하는데요.
 
그 상태에서 계속 Scan() 하면 파일이 끝나더라도 계속 false가 나올테니 Scan()을 최종 종료하기 위한 조건이 필요합니다.

**Comment by mrchypark** [comment]
https://github.com/codingpot/kiwigo/commit/92297db5e075cebe4a7e6fbab42c041dea3c53e0
